### ISSUE TITLE
Приватный конструктор в синглтоне

### ISSUE THREAD

**Issue by domosedov** [artikus11/art-frontend-posts#1]
https://github.com/artikus11/art-frontend-posts/blob/2c6239bf6872924444e0079a4371c8bf88a37d31/includes/class-afcp-core.php#L8

Для того, чтобы нельзя было создать больше одного экземпляра класса, конструктор нужно сделать приватным.

**Comment by artikus11** [comment]
Принято

**Comment by domosedov** [comment]
👍
